### ISSUE TITLE
Handling dynamic theme changes in IE11

### ISSUE THREAD

**Issue by mathisscott** [clr-team/planning#14]
## Description of work, pt. 1

- [x] Create a test branch
- [x] Add a basic web component to the devapp homepage, like a simple button
- [x] Create a couple of global level custom properties on things like button colors and another item
- [x] Add cssvars ponyfill to the devapp
- [x] Verify that they work
- [x] Implement a click handler that toggles these custom properties, giving them new values
- [x] Verify that this works in IE

## Description of work, pt. 2
- [x] ! - Review updates on topic branch to pull down any changes that we needed to fix IE (Lit is broken in IE, more polyfills are needed that we don't have, etc.)
- [x] Pull in updated css-vars-ponyfill to our project as a stopgap until next step PR is merged or declined
- [x] Review css-vars-ponyfill and optimized-vars-ponyfill to see what the optimizations are and if they will help speed up IE11 (2)(3)
- [ ] Submit PR to css-vars-ponyfill maintainer to expose the variableStore. We need it.
- [ ] Document how themes will be implemented in clarity-base when custom properties are in place (need to do this closer to release...)
- [x] Add a page for custom properties in the dev app
- [x] Rough up a CSS custom properties architecture, even a whiteboarding would be helpful
- [ ] (Optional?) Do a dev-share on all the issues we ran into
- [ ] (Optional?) Write a blogpost, even if we don't publish it for a few more months. 

Goal: Document what we need to do with the css polyfill (if anything) to make dynamic themes work in IE11. See: -SAP's web component library for changes they have made.- (SAP's approach is broken in the latest css-vars-ponyfill; maybe that is why they are frozen on a specific version?)

### Types of theming verified
- [x] Programmatically updating custom properties in javascript-land. This requires a two-pronged approach of adding stylesheets to the document (which css-vars can pick up) and then running `styleDocument()` in ShadyCSS. In the dev branch, this second step is handled automagically after the ponyfill updates.
- [x] Adding and removing (from the DOM) stylesheets that update custom properties

### Types of theming that will not work
- Overriding custom properties in the cascade. This is problematic for ShadyCSS and the ponyfill to integrate. It's best to keep all custom property declarations on `:root` selectors.
- Overriding custom properties by setting them programmatically via `setProperty`. The ponyfill doesn't realize that properties have been changed because it only watches for `<style>` and `<link>` element changes and doesn't know when it should run.

## Issue(s)

https://github.com/coryrylan/clarity-web-component-issues/issues/16

## Reviewers

* [ ] Bozhidar
* [x] Cory
* [ ] Ivan
* [x] Jeeyun
* [ ] Jeremy
* [ ] Matt
* [ ] Scott
* [ ] Shijir

## Definition of done

* [ ] Reviewed by peers

### Notes

1. This is an exploratory task to determine what gaps we have in IE11 support with custom properties and the css-vars-ponyfill. It may result in new code for clr-base or it may result in a topic branch that ultimately becomes documentation.
2. We need to judiciously set some flags on the css-vars-ponyfill. ShadyCSS is _not_ a perf drag. As a result, people changing themes will need to _manually_ call our helper function. Right now, initial page load in IE (dev-app) takes 10 seconds and switching a theme can take 30 seconds. With the performance changes, page load in IE takes around 8 seconds and switching themes takes 8-9 seconds. Note this is on a low-powered VM.
3. We have an option that we can use that further boosts IE performance – `preserveStatic: false`. Page load drops to 1.5 seconds and theme switching drops to around 300 milliseconds. But it limits what we can use custom properties for. We are hanging on to Option B for now, opting for more flexibility with custom properties and a slightly degraded IE experience.
4. If users want theming _and_ IE/OldDirtyEdge support, they will have to programmatically change values like in my branch. If users don't care about that and only want modern browsers, they can switch themes even in CSS by applying a class to the body tag or somesuch. That won't work in IE/OldDirtyEdge tho.

**Comment by mathisscott** [comment]
We have some work ahead of us on the polyfill side of things. Angular CLI, Polymer, and Angular 8 are not helping us when it comes to IE11 support. And @coryrylan and I expect that to only get worse over time.

At a high level, we had to transpile Lit Element to ES5 using a custom webpack plugin. This is something we will have to do with Lit Element. There is no way around it.

Additionally, there is a core-js shim we will need to add to polyfills.ts to avoid navigation issues in IE11 when dev-tools is active. This is not related to WCs. But it is emblematic of how IE11 support is an after-thought with these Google libraries.

The css-vars-ponyfill appears to be running alright at the moment. But we do still need to validate the dynamic theme updates.

**Comment by mathisscott** [comment]
Custom Properties architecture below...

![CustomPropertiesArchitecture](https://user-images.githubusercontent.com/2728359/62556098-d0f6e980-b839-11e9-9ac2-6eb97279a7f2.png)

**Comment by mathisscott** [comment]
The remaining few items are not a priority. So I'm deferring them to a point when I have more breathing room to address them or when I get a spot open to handle them.

**Comment by gnomeontherun** [comment]
Mostly resolved, will make new ticket for each remaining tasks.

**Comment by nuxodin** [comment]
Might be worth a try, this polyfill:
https://github.com/nuxodin/ie11CustomProperties
