### ISSUE TITLE
Keyboard driven focus reusable directive

### ISSUE THREAD

**Issue by Jinnie** [clr-team/planning#21]
## Description of work

A directive that will encapsulate all keyboard events, tabindex management, etc, so that it can be reused in menus, tabs, etc.

## Issue(s)

_Links to issues that it should resolve._

Fixes https://github.com/vmware/clarity/issues/

## Reviewers

* [ ] Bozhidar
* [ ] Cory
* [ ] Ivan
* [x] Jeeyun
* [ ] Jeremy
* [x] Matt
* [ ] Scott
* [ ] Shijir

## Definition of done

* [ ] Tests completed
* [ ] Reviewed by peers
* [ ] Design sign off (if necessary)
* [ ] Merged into master/topic branch

**Comment by jeeyun** [comment]
This will be interesting for me to review, as some of the work done for dropdown and combobox already include some of these functionalities.

**Comment by gnomeontherun** [comment]
@Jinnie Does this have potential to be used for https://github.com/vmware/clarity/issues/3569?

**Comment by Jinnie** [comment]
@gnomeontherun I can give it a test. It much depends on the tree structure. At least it can be used as a reference or be duplicated and modified to be used with the tree, as it encapsulates some fine details and corner cases.

**Comment by Jinnie** [comment]
Test done: 
https://stackblitz.com/edit/clarity-tree-proto?file=src/app/app.component.html
With very minor adjustments to the directive, the basics seem to be okay.
Still there is some more work to be done:
- make directive take button selectors as input parameters (or skip the class part and work with any button).
- make the tree open/close nodes with `<-` `->` keys
- check why the caret icon stops event propagation and it does not reach the button beneath - this leads to limited ability to change focus with mouse click
- prevent focus going to invisible element when `Home` or `End` button is pressed. Maybe allow home/end to be disabled on the directive, as it's not of huge value on a tree? Otherwise, something similar is done in the tabs/overflow PR.
