### ISSUE TITLE
Vertical nav focus management

### ISSUE THREAD

**Issue by Shijir** [clr-team/planning#30]
## Description of work

Vertical nav links do not navigate screen reader users to new content when the link is clicked and the page isn't a full page reload (Angular routing).

## Issue(s)

https://github.com/vmware/clarity/issues/3577

## Reviewers

* [ ] Colin
* [ ] Cory
* [ ] Matt

## Definition of done

* [ ] Tests completed
* [ ] Reviewed by peers
* [ ] Design sign off (if necessary)
* [ ] Merged into master/topic branch
* [ ] Backport (if necessary)

**Comment by gnomeontherun** [comment]
Hey @Shijir have you made any progress on this one yet or is it still waiting?
