### ISSUE TITLE
Dropdown disabled item a11y

### ISSUE THREAD

**Issue by jeeyun** [clr-team/planning#35]
## Description of work

Need to figure out if we are going to make disabled items in dropdown focusable (currently it is not). Separating this out from the rest of dropdown a11y bugs, since they are already merged in for next release. Scope of this is somewhat unknown and depends on the solution we pick.

Guidance: https://www.w3.org/TR/wai-aria-practices-1.1/#menu

Accessible example: https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-2/menubar-2.html

Figma draft: https://www.figma.com/file/B73U3X3LXZjrxVQvbnFAU6jy/dropdown-disabled-item-a11y?node-id=0%3A1

## Issue(s)

* https://github.com/vmware/clarity/issues/3602

## Reviewers

* Bozhidar
* Colin
* Cory
* Ivan
* Jeeyun
* Jeremy
* Matt
* Scott
* Shijir

## Definition of done

* [x] Tests completed
* [ ] Reviewed by peers
* [ ] Design sign off (if necessary)
* [ ] Merged into master/topic branch
* [ ] Backport (if necessary)

**Comment by colinreedmiller** [comment]
Initially it was believed that changing from aria-active-descendent required more effort than was possible to devote to this. Consequently a design honoring the focus ring remaining on the composite was created and prototyped:

https://www.figma.com/file/uc4cBSpP7rFB1YOhXlzHrM/Disabled-menu-items-should-be-focusable-3602?node-id=0%3A1

Subsequent investigation has revealed more options including the possibility of switching to the roving-tab-order method. Current direction from design is to mimic the native browser focus indication, applying this to disabled dropdown items.
