### ISSUE TITLE
Research progress bar color a11y plan

### ISSUE THREAD

**Issue by gnomeontherun** [clr-team/planning#50]
## Description of work

Research the progress bar implementation with its many variations and determine appropriate accessible options for the color variations (which are not accessible for color blind users).

## Issue(s)

* https://github.com/vmware/clarity/issues/3517

## Reviewers

* Chris

## Definition of done

* [ ] Proposal of options
* [ ] Update implementation ticket with details

**Comment by colinreedmiller** [comment]
https://www.figma.com/file/5nR5pqc9eTT8idv7dWicks/Progress-color-3517?node-id=0%3A1

**Comment by colinreedmiller** [comment]
Previous file obsolete - new file:

https://www.figma.com/file/IHoMcemSsDuRw9waltUW8n/Progress-color-3517?node-id=0%3A1

**Comment by colinreedmiller** [comment]
Initial survey of options explored as ruff visual design and validated with a11y for pros and cons. Next step is to research and elicit feedback from product teams.

**Comment by colinreedmiller** [comment]
re: Eliminating color support specifically to status Success and Danger / Warning

VMC - Chit-Meng - Does not use / does not need
CSP - Alex - Does not use / does not need

With a few more data points for validation, this component can be documented to support user color without the specific indications of color as status coding.
(Status may be communicated with different devices).

**Comment by gnomeontherun** [comment]
Next step is to make the decision on documentation updates or design changes, then create the implementation ticket.

**Comment by colinreedmiller** [comment]
Survey from product teams is complete and unanimous - comment above updated. No one I spoke with is using the red or green progress bars to convey warning / success messaging. 

Recommendation is to leave the design as-is, allow non-message bearing color variants in progress bars, but to remove guidance from documentation re: success / warning and update it to give guidance on using color for visual design reasons including a11y admonitions.

**Comment by colinreedmiller** [comment]
Complete - new issue for documentation update opened #87
