### ISSUE TITLE
Keyboard interaction for Tree View

### ISSUE THREAD

**Issue by gnomeontherun** [clr-team/planning#66]
## Description of work

The Tree View does not support the correct keyboard interactions. Currently , tree nodes can be focused with the Tab key and activated with the Enter key. But the main behaviors expected for trees are as follows.

The entire tree structure should be focusable as a whole when using the Tab key
When the tree has focus, the user should be able to use the arrow keys to navigate the nodes in the tree in any direction depending on the complexity of the tree.
See the rest of the expected keyboard interactions at https://www.w3.org/TR/wai-aria-practices-1.1/#TreeView below.

## Issue(s)

* https://github.com/vmware/clarity/issues/

## Reviewers

* Bozhidar
* Chris
* Cory

## Definition of done

* [ ] Tests completed
* [ ] Reviewed by peers
* [ ] Design sign off (if necessary)
* [ ] Merged into master/topic branch
* [ ] Backport (if necessary)

**Comment by gnomeontherun** [comment]
@Jinnie Will your utility help address this need?

**Comment by Jinnie** [comment]
@gnomeontherun Yes, as I mentioned here after doing a test stackblitz, it can:
https://github.com/clr-team/planning/issues/21

I hope the initial commit for the directive will be very soon, so I can also take this one after this.
