### ISSUE TITLE
Datagrid built-in filter that allows user to select from a list of values in the column research

### ISSUE THREAD

**Issue by colinreedmiller** [clr-team/planning#78]
Examine existing components and implementations of this function.
competitive analysis
Visual design research
Expose use cases to validate against VMware products.

**Comment by colinreedmiller** [comment]
https://www.figma.com/file/DxLEcHBTqEZIK0ta02t9Ec/Datagrid-filter-1175?node-id=0%3A1

**Comment by gnomeontherun** [comment]
Moved to backlog, meaningful but lower priority.
