### ISSUE TITLE
Update documentation for progress color

### ISSUE THREAD

**Issue by colinreedmiller** [clr-team/planning#87]
Red / Warning and Green / Success progress bars are not accessible when the use of color is intended to convey meaning. Research indicates that teams are not employing this attribute as specified in the documentation. Design changes and removing this guidance have been both examined, and the finding is that the guidance will be removed and thus the documentation must be updated.

Update visual / demo and written documentation for progress bar color to remove color as status indication. New documentation should specify that colors in addition to action blue may be used but only for visual design reasons, and that using color to convey meaning is not supported.

**Comment by colinreedmiller** [comment]
https://www.figma.com/file/P1otVcRTXOPovGzVKpY4Us/Update-documentation-for-progress-color-87?node-id=0%3A1

**Comment by colinreedmiller** [comment]
001 - No changes needed
Progress
Labeled
Fade out
Indeterminate / looping

002 - Changes - see design: https://www.figma.com/file/P1otVcRTXOPovGzVKpY4Us/Update-documentation-for-progress-color-87?node-id=0%3A1

003 - Animation - Changes:
Flash Red then fade - remove
Labeled With Success Flash And Fade - remove

004 - Variations - these 5 should be deprecated:

1. flash: A progress container with the flash classname will have the bar color change to green after it reaches 100%. This can be combined with the progress-fade classname to have the bar change color to green and then fade out.

2. flash-danger: A progress container with the flash-danger classname will have the bar color change to red after it reaches 100%. This classname can also be combined with the progress-fade classname.

3. danger: A progress container with the danger classname will show up as red.
4. warning: A progress container with the warning classname will also show up as red.
5. success: A progress container with the success classname will show up as green.

005 In progress / in sidebar - no changes

006 - Static Progress Bars
Red Static Progress Bar - remove
Green Static Progress Bar- remove

007 - Progress Bar Blocks and Groups
Notes should include guidance to consider accessible colors when using multiple progress, and not to use color as the sole method of communicating status such as success or danger/warning.

008 - Component code
These should be removed:
[clrFlashDanger]	Boolean	false	Flash in danger animation
[clrSuccess]	Boolean	false	Add success style
[clrDanger]	Boolean	false	Add danger style

**Comment by colinreedmiller** [comment]
Please review:

- [ ] Jeremy
- [ ] Scott

**Comment by mathisscott** [comment]
LGTM. These will constitute breaking changes from an API standpoint so should we do the deprecations in 3.0 for removal in 4.0? Perhaps giving an alert noting that they are both deprecated and should be avoided for a11y reasons?

**Comment by gnomeontherun** [comment]
My only real comment is that by deprecating and removing the variations we expect for folks to set their own colors in CSS right? I think it would be good to retain several 'blessed' variations (particularly in a stacked progress bar example) but the docs additions should indicate that color doesn't indicate meaning by itself.

**Comment by colinreedmiller** [comment]
So for docs we have a set of colors that includes:
action-blue
alt-color-1
alt-color-2
or custom

Note: keep in mind a11y when using color in progress:
colorblind (stacked)
and screen reader (color cannot be the only meaning conveying device).

**Comment by colinreedmiller** [comment]
Figma file is updated to include 3 alt colors and a note regarding how to document this.

https://www.figma.com/file/P1otVcRTXOPovGzVKpY4Us/Update-documentation-for-progress-color-87?node-id=0%3A1

**Comment by colinreedmiller** [comment]
Further discussion re: alt-colors s supplied by Clarity - decision . is that Clarity will provide default and override as the only options. Updated spec.

**Comment by gnomeontherun** [comment]
Ready for implementation on dev side.
