### ISSUE TITLE
Validate circular progress design with product teams

### ISSUE THREAD

**Issue by colinreedmiller** [clr-team/planning#89]
Circular progress design currently has several sizes from a very small determinate spinner type that may be used in cards and navigation, all the way to a much larger gauge type. Reviewing this design with several product teams will inform us which sizes should be built.

**Comment by mathisscott** [comment]
Would it make sense to treat these as separate things?

1) a small determinate spinner
2) a larger gauge

**Comment by colinreedmiller** [comment]
@mathisscott 
Indeed it would.

The small determinate spinner type progress bar is simple enough and just needs to be checked with product teams for use case validation. A gauge type design is simultaneously part of the same concept but also quickly becomes something different. The best path forward is to review the existing sizes with the limitation of them only being applied to the use case of displaying progress.

The gauge investigation will be better to bundle with the charts work.
