### ISSUE TITLE
Sidenav collapse menu item cannot be focused

### ISSUE THREAD

**Issue by hippee-lee** [clr-team/planning#93]
## Description of work

The sidenav collapsable nav menu titles are not focusable with keyboard.

## Issue(s)

* https://github.com/vmware/clarity/issues/3526

## Reviewers

tbd

## Definition of done

* [x] Tests completed
* [x] Reviewed by peers
* [ ] Design sign off (if necessary)
* [x] Merged into master/topic branch
* [x] Backport (if necessary)

**Comment by hippee-lee** [comment]
Triaging this while #44 is blocked

**Comment by gnomeontherun** [comment]
Duplicate of #63
